ALTER TABLE "restaurants" ADD COLUMN IF NOT EXISTS "maxBotToken" TEXT;
ALTER TABLE "restaurants" ADD COLUMN IF NOT EXISTS "maxBotActive" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "maxUserId" TEXT;
